blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://pharaonic.dev/packages/laravel/hijri
    about: Read the Pharaonic documentation.
  - name: Community support
    url: https://discord.gg/XQG9RhvEvf
    about: Get help from the Pharaonic Discord community.
